name: PS PipeLine
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Test src
        run: |
          pip3 install pytest
          python3 -m pytest > test.txt
          cat test.txt
          
      - name: Copy result of testing
        uses: actions/upload-artifact@v2
        with:
          name: test
          path: test.txt
